sudo: required
services: docker
language: minimal

env:
  - TEST_CASE=1.8
  - TEST_CASE=1.9
  - TEST_CASE=1.10
  - TEST_CASE=ipv6-only TEST_K7S_VER='v1.9'
  - TEST_CASE=ipv6-only TEST_K8S_VER='v1.9' DIND_ALLOW_AAAA_USE=true
  - TEST_CASE=ipv6-only TEST_K8S_VER='v1.10'
  - TEST_CASE=ipv6-only TEST_K8S_VER='v1.10' DIND_ALLOW_AAAA_USE=true
  - TEST_CASE=ipv6-only TEST_K8S_VER='v1.11'
  - TEST_CASE=ipv6-only TEST_K8S_VER='v1.11' DIND_ALLOW_AAAA_USE=true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y liblz4-tool

script:
  # building k8s may cause Travis to time out w/o output
  - if [ -n "${TWAIT:-}" ]; then travis_wait 35 ./test.sh; else ./test.sh; fi

before_script:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
